// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:tiny_audio_player/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(PlaylistModeAdapter());
    registerAdapter(SerializedMediaAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(PlaylistModeAdapter());
    registerAdapter(SerializedMediaAdapter());
  }
}
